---
language: python
dist: focal
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  - pip install -r test-requirements.txt

script:
  - molecule test

# rename project directory to match Galaxy role name
before_script:
  - cd ../
  - mv ansible-sane bodsch.sane
  - cd bodsch.sane

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
